# *Data Cleaning Walkthrough*

**For the purposes of this project, we'll be using data about New York City public schools, which can be found <a href="https://data.cityofnewyork.us/browse?category=Education">here</a>.<br> Below are the datasets that we will be using:**

<a href="https://data.cityofnewyork.us/Education/SAT-Results/f9bf-2cp4">SAT scores by school</a> - SAT scores for each high school in New York City<br>
<a href="https://data.cityofnewyork.us/Education/School-Attendance-and-Enrollment-Statistics-by-Dis/7z8d-msnt">School attendance</a> - Attendance information for each school in New York City<br>
<a href="https://data.cityofnewyork.us/Education/2010-2011-Class-Size-School-level-detail/urz7-pzb3">Class size</a> - Information on class size for each school<br>
<a href="https://data.cityofnewyork.us/Education/AP-College-Board-2010-School-Level-Results/itfs-ms3e">AP test results</a> - Advanced Placement (AP) exam results for each high school (passing an optional AP exam in a particular subject can earn a student college credit in that subject)<br>
<a href="https://data.cityofnewyork.us/Education/Graduation-Outcomes-Classes-Of-2005-2010-School-Le/vh2h-md7a">Graduation outcomes</a> - The percentage of students who graduated, and other outcome information<br>
<a href="https://data.cityofnewyork.us/Education/School-Demographics-and-Accountability-Snapshot-20/ihfw-zy9j">Demographics</a> - Demographic information for each school<br>
<a href="https://data.cityofnewyork.us/Education/NYC-School-Survey-2011/mnz3-dyi8">School survey</a> - Surveys of parents, teachers, and students at each school<br>

**All of these data sets are interrelated. We'll need to combine them into a single data set before we can find correlations.**

### Reading The Data

1. Read each of the files in the list data_files into a pandas dataframe using the pandas.read_csv() function.
    - Recall that all of the data sets are in the schools folder. That means the path to ap_2010.csv is schools/ap_2010.csv.
2. Add each of the dataframes to the dictionary data, using the base of the filename as the key. For example, you'd enter ap_2010 for the file ap_2010.csv.
3. Afterwards, data should have the following keys:
    - ap_2010
    - class_size
    - demographics
    - graduation
    - hs_directory
    - sat_results
4. In addition, each key in data should have the corresponding dataframe as its value.

In [1]:
import pandas as pd
data_files = [
    "ap_2010.csv",
    "class_size.csv",
    "demographics.csv",
    "graduation.csv",
    "hs_directory.csv",
    "sat_results.csv"
]
data = {}

for item in data_files:
    data[item[:-4]] = pd.read_csv("schools/%s" % item)
    
data

{'ap_2010':         DBN                                         SchoolName  \
 0    01M448                       UNIVERSITY NEIGHBORHOOD H.S.
 1    01M450                             EAST SIDE COMMUNITY HS
 2    01M515                                LOWER EASTSIDE PREP
 3    01M539                     NEW EXPLORATIONS SCI,TECH,MATH
 4    02M296              High School of Hospitality Management
 5    02M298                                   Pace High School
 6    02M300  Urban Assembly School of Design and Construction,
 7    02M303                         Facing History School, The
 8    02M305  Urban Assembly Academy of Government and Law, The
 9    02M308                       Lower Manhattan Arts Academy
 10   02M400                       HS FOR ENVIRONMENTAL STUDIES
 11   02M408                       PROFESSIONAL PERFORMING ARTS
 12   02M411                           BARUCH COLLEGE CAMPUS HS
 13   02M412                       NYC LAB HS FOR COLL. STUDIES
 14   02M413                               SCHOOL OF THE FUTURE
 15   02M414                                  NYC MUSEUM SCHOOL
 16   02M416                      Eleanor Roosevelt High School
 17   02M418                             Millennium High School
 18   02M420                           HEALTH PROF & HUMAN SVCS
 19   02M425                        H S FOR LEADERSHIP & PUBLIC
 20   02M429                                      LEGACY SCHOOL
 21   02M439                       MANHATTAN VILLAGE ACADEMY HS
 22   02M440                                  HS FOR HUMANITIES
 23   02M459                        CES-MANHATTAN INTERNATIONAL
 24   02M460                               WASHINGTON IRVING HS
 25   02M475                                      STUYVESANT HS
 26   02M489                          HS OF ECONOMICS & FINANCE
 27   02M519                                   TALENT UNLIMITED
 28   02M520                               MURRY BERGTRAUM H.S.
 29   02M529                           JACQUELINE K. ONASSIS HS
 ..      ...                                                ...
 228  28Q620                                  THOS A EDISON VHS
 229  28Q680                         GATEWAY TO HEALTH SCIENCES
 230  28Q687                Queens HS for Science York Colllege
 231  28Q690  High School for Law Enforcement and Public Safety
 232  28Q896           Young  Women's Leadership School, Queens
 233  29Q248                         Queens Preparatory Academy
 234  29Q259  Pathways College Preparatory School: A College...
 235  29Q272  George Washington Carver High School for the S...
 236  29Q283                    Preparatory Academy for Writers
 237  29Q420                             SPRINGFIELD GARDENS HS
 238  29Q492                     MATH/SCIENCE RESEARCH TECH CTR
 239  29Q496                     BUSINESS/COMPUTER APPLICATIONS
 240  30Q445                                WM CULLEN BRYANT HS
 241  30Q450                                LONG ISLAND CITY HS
 242  30Q501                          FRANK SINATRA HIGH SCHOOL
 243  30Q502                          INFORMATION TECHNOLOGY HS
 244  30Q555                         NEWCOMERS HS:ACAD AMER STD
 245  30Q575                        ACADEMY OF AMER. STUDIES HS
 246  31R080                         PS 080 MICHAEL J. PETRIDES
 247  31R440                                        NEW DORP HS
 248  31R445                                   PORT RICHMOND HS
 249  31R450                                          CURTIS HS
 250  31R455                                     TOTTENVILLE HS
 251  31R460                                 SUSAN E. WAGNER HS
 252  31R600                                    RAPLH MCKEE VHS
 253  31R605                         STATEN ISLAND TECHNICAL HS
 254  32K545                      EBC-HS FOR PUB SERVICE (BUSH)
 255  32K552                          Academy of Urban Planning
 256  32K554               All City Leadership Secondary School
 257  32K556  Bushwick Leaders High School for Academic Exce...

     AP Test Takers  Total Exams Taken Number of Exams with scores 3 4 or 5
 0                39                49                                   10
 1                19                21                                    s
 2                24                26                                   24
 3               255               377                                  191
 4                 s                 s                                    s
 5                21                21                                    s
 6                99               117                                   10
 7                42                44                                    s
 8                25                37                                   15
 9                 s                 s                                    s
 10              213               298                                  152
 11               20                20                                   15
 12               78               115                                   88
 13              114               140                                   97
 14               11                11                                    s
 15                s                 s                                    s
 16              155               235                                  169
 17               86                95                                   67
 18              204               248                                   75
 19               70                84                                   32
 20               22                26                                    s
 21               42                69                                   29
 22                6                 6                                    s
 23               12                12                                    6
 24               69                83                                   21
 25             1510              2819                                 2648
 26              101               176                                   78
 27               30                34                                   21
 28              118               157                                   76
 29               80               118                                   29
 ..              ...               ...                                  ...
 228             183               244                                  100
 229              89               136                                   57
 230             215               338                                  275
 231              19                19                                    s
 232               6                 6                                    s
 233              15                15                                    s
 234              29                71                                    s
 235              14                21                                    s
 236              40                43                                    s
 237               s                 s                                    s
 238              22                31                                    8
 239               s                 s                                    s
 240             243               330                                   97
 241             406               805                                  169
 242             108               136                                   38
 243              51                74                                   13
 244             119               163                                  140
 245             101               170                                  119
 246             162               243                                   66
 247              96               118                                   62
 248             194               304                                   76
 249             247               295                                   90
 250             396               687                                  206
 251             279               408                                  175
 252               s                 s                                    s
 253             528               905                                  809
 254              47                64                                   13
 255              76               100                                   10
 256               7                 8                                    s
 257              34                35                                   18

 [258 rows x 5 columns], 'class_size':        CSD BOROUGH SCHOOL CODE  \
 0        1       M        M015
 1        1       M        M015
 2        1       M        M015
 3        1       M        M015
 4        1       M        M015
 5        1       M        M015
 6        1       M        M015
 7        1       M        M015
 8        1       M        M015
 9        1       M        M015
 10       1       M        M015
 11       1       M        M015
 12       1       M        M019
 13       1       M        M019
 14       1       M        M019
 15       1       M        M019
 16       1       M        M019
 17       1       M        M019
 18       1       M        M019
 19       1       M        M019
 20       1       M        M019
 21       1       M        M019
 22       1       M        M019
 23       1       M        M019
 24       1       M        M019
 25       1       M        M020
 26       1       M        M020
 27       1       M        M020
 28       1       M        M020
 29       1       M        M020
 ...    ...     ...         ...
 27581   32       K        K556
 27582   32       K        K556
 27583   32       K        K556
 27584   32       K        K556
 27585   32       K        K556
 27586   32       K        K556
 27587   32       K        K556
 27588   32       K        K556
 27589   32       K        K556
 27590   32       K        K556
 27591   32       K        K556
 27592   32       K        K556
 27593   32       K        K556
 27594   32       K        K556
 27595   32       K        K564
 27596   32       K        K564
 27597   32       K        K564
 27598   32       K        K564
 27599   32       K        K564
 27600   32       K        K564
 27601   32       K        K564
 27602   32       K        K564
 27603   32       K        K564
 27604   32       K        K564
 27605   32       K        K564
 27606   32       K        K564
 27607   32       K        K564
 27608   32       K        K564
 27609   32       K        K564
 27610   32       K        K564

                                              SCHOOL NAME GRADE  PROGRAM TYPE  \
 0                              P.S. 015 Roberto Clemente     0K       GEN ED
 1                              P.S. 015 Roberto Clemente     0K          CTT
 2                              P.S. 015 Roberto Clemente     01       GEN ED
 3                              P.S. 015 Roberto Clemente     01          CTT
 4                              P.S. 015 Roberto Clemente     02       GEN ED
 5                              P.S. 015 Roberto Clemente     02          CTT
 6                              P.S. 015 Roberto Clemente     03       GEN ED
 7                              P.S. 015 Roberto Clemente     03          CTT
 8                              P.S. 015 Roberto Clemente     04       GEN ED
 9                              P.S. 015 Roberto Clemente     05       GEN ED
 10                             P.S. 015 Roberto Clemente  0K-09      SPEC ED
 11                             P.S. 015 Roberto Clemente    NaN          NaN
 12                                   P.S. 019 Asher Levy     0K       GEN ED
 13                                   P.S. 019 Asher Levy     0K          CTT
 14                                   P.S. 019 Asher Levy     01       GEN ED
 15                                   P.S. 019 Asher Levy     01          CTT
 16                                   P.S. 019 Asher Levy     02       GEN ED
 17                                   P.S. 019 Asher Levy     03       GEN ED
 18                                   P.S. 019 Asher Levy     04       GEN ED
 19                                   P.S. 019 Asher Levy     04          CTT
 20                                   P.S. 019 Asher Levy     05       GEN ED
 21                                   P.S. 019 Asher Levy     05          CTT
 22                                   P.S. 019 Asher Levy  0K-09      SPEC ED
 23                                   P.S. 019 Asher Levy  0K-09      SPEC ED
 24                                   P.S. 019 Asher Levy    NaN          NaN
 25                                  P.S. 020 Anna Silver     0K       GEN ED
 26                                  P.S. 020 Anna Silver     0K          CTT
 27                                  P.S. 020 Anna Silver     01       GEN ED
 28                                  P.S. 020 Anna Silver     01          CTT
 29                                  P.S. 020 Anna Silver     02       GEN ED
 ...                                                  ...    ...          ...
 27581  Bushwick Leaders High School for Academic Exce...  09-12       GEN ED
 27582  Bushwick Leaders High School for Academic Exce...  09-12       GEN ED
 27583  Bushwick Leaders High School for Academic Exce...  09-12       GEN ED
 27584  Bushwick Leaders High School for Academic Exce...  09-12       GEN ED
 27585  Bushwick Leaders High School for Academic Exce...  09-12       GEN ED
 27586  Bushwick Leaders High School for Academic Exce...  09-12      SPEC ED
 27587  Bushwick Leaders High School for Academic Exce...  09-12      SPEC ED
 27588  Bushwick Leaders High School for Academic Exce...  09-12      SPEC ED
 27589  Bushwick Leaders High School for Academic Exce...  09-12      SPEC ED
 27590  Bushwick Leaders High School for Academic Exce...  09-12      SPEC ED
 27591  Bushwick Leaders High School for Academic Exce...  09-12      SPEC ED
 27592  Bushwick Leaders High School for Academic Exce...  09-12      SPEC ED
 27593  Bushwick Leaders High School for Academic Exce...  09-12      SPEC ED
 27594  Bushwick Leaders High School for Academic Exce...    NaN          NaN
 27595                     Bushwick Community High School  09-12       GEN ED
 27596                     Bushwick Community High School  09-12       GEN ED
 27597                     Bushwick Community High School  09-12       GEN ED
 27598                     Bushwick Community High School  09-12       GEN ED
 27599                     Bushwick Community High School  09-12       GEN ED
 27600                     Bushwick Community High School  09-12       GEN ED
 27601                     Bushwick Community High School  09-12       GEN ED
 27602                     Bushwick Community High School  09-12       GEN ED
 27603                     Bushwick Community High School  09-12       GEN ED
 27604                     Bushwick Community High School  09-12       GEN ED
 27605                     Bushwick Community High School  09-12       GEN ED
 27606                     Bushwick Community High School  09-12       GEN ED
 27607                     Bushwick Community High School  09-12       GEN ED
 27608                     Bushwick Community High School  09-12       GEN ED
 27609                     Bushwick Community High School  09-12          CTT
 27610                     Bushwick Community High School    NaN          NaN

       CORE SUBJECT (MS CORE and 9-12 ONLY)  \
 0                                        -
 1                                        -
 2                                        -
 3                                        -
 4                                        -
 5                                        -
 6                                        -
 7                                        -
 8                                        -
 9                                        -
 10                                       -
 11                                     NaN
 12                                       -
 13                                       -
 14                                       -
 15                                       -
 16                                       -
 17                                       -
 18                                       -
 19                                       -
 20                                       -
 21                                       -
 22                                       -
 23                                       -
 24                                     NaN
 25                                       -
 26                                       -
 27                                       -
 28                                       -
 29                                       -
 ...                                    ...
 27581                              SCIENCE
 27582                       SOCIAL STUDIES
 27583                       SOCIAL STUDIES
 27584                       SOCIAL STUDIES
 27585                       SOCIAL STUDIES
 27586                              ENGLISH
 27587                              ENGLISH
 27588                              ENGLISH
 27589                                 MATH
 27590                              SCIENCE
 27591                              SCIENCE
 27592                              SCIENCE
 27593                       SOCIAL STUDIES
 27594                                  NaN
 27595                              ENGLISH
 27596                              ENGLISH
 27597                              ENGLISH
 27598                              ENGLISH
 27599                                 MATH
 27600                                 MATH
 27601                              SCIENCE
 27602                              SCIENCE
 27603                              SCIENCE
 27604                              SCIENCE
 27605                       SOCIAL STUDIES
 27606                       SOCIAL STUDIES
 27607                       SOCIAL STUDIES
 27608                       SOCIAL STUDIES
 27609                                 MATH
 27610                                  NaN

       CORE COURSE (MS CORE and 9-12 ONLY) SERVICE CATEGORY(K-9* ONLY)  \
 0                                       -                           -
 1                                       -                           -
 2                                       -                           -
 3                                       -                           -
 4                                       -                           -
 5                                       -                           -
 6                                       -                           -
 7                                       -                           -
 8                                       -                           -
 9                                       -                           -
 10                                      -                      12:1:1
 11                                    NaN                         NaN
 12                                      -                           -
 13                                      -                           -
 14                                      -                           -
 15                                      -                           -
 16                                      -                           -
 17                                      -                           -
 18                                      -                           -
 19                                      -                           -
 20                                      -                           -
 21                                      -                           -

### Exploring the SAT Data 
1. Display the first five rows of the SAT scores data.
    - Use the key sat_results to access the SAT scores dataframe stored in the dictionary data.
    - Use the pandas.DataFrame.head() method along with the print() function to display the first five rows of the dataframe.

In [2]:
data['sat_results'][:5]

,DBN,SCHOOL NAME,Num of SAT Test Takers,SAT Critical Reading Avg. Score,SAT Math Avg. Score,SAT Writing Avg. Score
0,01M292,HENRY STREET SCHOOL FOR INTERNATIONAL STUDIES,29,355,404,363
1,01M448,UNIVERSITY NEIGHBORHOOD HIGH SCHOOL,91,383,423,366
2,01M450,EAST SIDE COMMUNITY SCHOOL,70,377,402,370
3,01M458,FORSYTH SATELLITE ACADEMY,7,414,401,359
4,01M509,MARTA VALLE HIGH SCHOOL,44,390,433,384

### Exploring the Remaining Data
1. Loop through each key in data. For each key:
    - Display the first five rows of the dataframe associated with the key.

In [3]:
for item in data:
    print('\n%s\n' % item)
    print(data[item][:5])

ap_2010

      DBN                             SchoolName AP Test Takers   \
0  01M448           UNIVERSITY NEIGHBORHOOD H.S.              39
1  01M450                 EAST SIDE COMMUNITY HS              19
2  01M515                    LOWER EASTSIDE PREP              24
3  01M539         NEW EXPLORATIONS SCI,TECH,MATH             255
4  02M296  High School of Hospitality Management               s

  Total Exams Taken Number of Exams with scores 3 4 or 5
0                49                                   10
1                21                                    s
2                26                                   24
3               377                                  191
4                 s                                    s

class_size

   CSD BOROUGH SCHOOL CODE                SCHOOL NAME GRADE  PROGRAM TYPE  \
0    1       M        M015  P.S. 015 Roberto Clemente     0K       GEN ED
1    1       M        M015  P.S. 015 Roberto Clemente     0K          CTT
2    1       M        M015  P.S. 015 Roberto Clemente     01       GEN ED
3    1       M        M015  P.S. 015 Roberto Clemente     01          CTT
4    1       M        M015  P.S. 015 Roberto Clemente     02       GEN ED

  CORE SUBJECT (MS CORE and 9-12 ONLY) CORE COURSE (MS CORE and 9-12 ONLY)  \
0                                    -                                   -
1                                    -                                   -
2                                    -                                   -
3                                    -                                   -
4                                    -                                   -

  SERVICE CATEGORY(K-9* ONLY)  NUMBER OF STUDENTS / SEATS FILLED  \
0                           -                               19.0
1                           -                               21.0
2                           -                               17.0
3                           -                               17.0
4                           -                               15.0

   NUMBER OF SECTIONS  AVERAGE CLASS SIZE  SIZE OF SMALLEST CLASS  \
0                 1.0                19.0                    19.0
1                 1.0                21.0                    21.0
2                 1.0                17.0                    17.0
3                 1.0                17.0                    17.0
4                 1.0                15.0                    15.0

   SIZE OF LARGEST CLASS DATA SOURCE  SCHOOLWIDE PUPIL-TEACHER RATIO
0                   19.0         ATS                             NaN
1                   21.0         ATS                             NaN
2                   17.0         ATS                             NaN
3                   17.0         ATS                             NaN
4                   15.0         ATS                             NaN

demographics

      DBN                       Name  schoolyear fl_percent  frl_percent  \
0  01M015  P.S. 015 ROBERTO CLEMENTE    20052006       89.4          NaN
1  01M015  P.S. 015 ROBERTO CLEMENTE    20062007       89.4          NaN
2  01M015  P.S. 015 ROBERTO CLEMENTE    20072008       89.4          NaN
3  01M015  P.S. 015 ROBERTO CLEMENTE    20082009       89.4          NaN
4  01M015  P.S. 015 ROBERTO CLEMENTE    20092010                    96.5

   total_enrollment prek   k grade1 grade2    ...     black_num black_per  \
0               281   15  36     40     33    ...            74      26.3
1               243   15  29     39     38    ...            68      28.0
2               261   18  43     39     36    ...            77      29.5
3               252   17  37     44     32    ...            75      29.8
4               208   16  40     28     32    ...            67      32.2

  hispanic_num hispanic_per white_num white_per male_num male_per female_num  \
0          189         67.3         5       1.8    158.0     56.2      123.0
1          153         63.0         4       1.6    140.0     57.6      103.0
2          157         60.2         7       2.7    143.0     54.8      118.0
3          149         59.1         7       2.8    149.0     59.1      103.0
4          118         56.7         6       2.9    124.0     59.6       84.0

  female_per
0       43.8
1       42.4
2       45.2
3       40.9
4       40.4

[5 rows x 38 columns]

graduation

    Demographic     DBN                            School Name    Cohort  \
0  Total Cohort  01M292  HENRY STREET SCHOOL FOR INTERNATIONAL      2003
1  Total Cohort  01M292  HENRY STREET SCHOOL FOR INTERNATIONAL      2004
2  Total Cohort  01M292  HENRY STREET SCHOOL FOR INTERNATIONAL      2005
3  Total Cohort  01M292  HENRY STREET SCHOOL FOR INTERNATIONAL      2006
4  Total Cohort  01M292  HENRY STREET SCHOOL FOR INTERNATIONAL  2006 Aug

   Total Cohort Total Grads - n Total Grads - % of cohort Total Regents - n  \
0             5               s                         s                 s
1            55              37                      67.3                17
2            64              43                      67.2                27
3            78              43                      55.1                36
4            78              44                      56.4                37

  Total Regents - % of cohort Total Regents - % of grads  \
0                           s                          s
1                        30.9                       45.9
2                        42.2                       62.8
3                        46.2                       83.7
4                        47.4                       84.1

             ...            Regents w/o Advanced - n  \
0            ...                                   s
1            ...                                  17
2            ...                                  27
3            ...                                  36
4            ...                                  37

  Regents w/o Advanced - % of cohort Regents w/o Advanced - % of grads  \
0                                  s                                 s
1                               30.9                              45.9
2                               42.2                              62.8
3                               46.2                              83.7
4                               47.4                              84.1

  Local - n Local - % of cohort  Local - % of grads Still Enrolled - n  \
0         s                   s                   s                  s
1        20                36.4                54.1                 15
2        16                  25  37.200000000000003                  9
3         7                   9                16.3                 16
4         7                   9                15.9                 15

  Still Enrolled - % of cohort Dropped Out - n Dropped Out - % of cohort
0                            s               s                         s
1                         27.3               3                       5.5
2                         14.1               9                      14.1
3                         20.5              11                      14.1
4                         19.2              11                      14.1

[5 rows x 23 columns]

hs_directory

      dbn                                        school_name    borough  \
0  17K548                Brooklyn School for Music & Theatre   Brooklyn
1  09X543                   High School for Violin and Dance      Bronx
2  09X327        Comprehensive Model School Project M.S. 327      Bronx
3  02M280     Manhattan Early College School for Advertising  Manhattan
4  28Q680  Queens Gateway to Health Sciences Secondary Sc...     Queens

  building_code    phone_number    fax_number  grade_span_min  grade_span_max  \
0          K440    718-230-6250  718-230-6262             9.0              12
1          X400    718-842-0687  718-589-9849             9.0              12
2          X240    718-294-8111  718-294-8109             6.0              12
3          M520  718-935-3477             NaN             9.0              10
4          Q695    718-969-3155  718-969-3552             6.0              12

   expgrade_span_min  expgrade_span_max  \
0                NaN                NaN
1                NaN                NaN
2                NaN                NaN
3                9.0               14.0
4                NaN                NaN

                         ...                         priority08 priority09  \
0                        ...                                NaN        NaN
1                        ...                                NaN        NaN
2                        ...                                NaN        NaN
3                        ...                                NaN        NaN
4                        ...                                NaN        NaN

  priority10                                         Location 1  \
0        NaN  883 Classon Avenue\nBrooklyn, NY 11225\n(40.67...
1        NaN  1110 Boston Road\nBronx, NY 10456\n(40.8276026...
2        NaN  1501 Jerome Avenue\nBronx, NY 10452\n(40.84241...
3        NaN  411 Pearl Street\nNew York, NY 10038\n(40.7106...
4        NaN  160 20 Goethals Avenue\nJamaica, NY 11432\n(40...

  Community Board  Council District Census Tract        BIN           BBL  \
0             9.0              35.0        213.0  3029686.0  3.011870e+09
1             3.0              16.0        135.0  2004526.0  2.026340e+09
2             4.0              14.0        209.0  2008336.0  2.028590e+09
3             1.0               1.0         29.0  1001388.0  1.001130e+09
4             8.0              24.0       1267.0  4539721.0  4.068580e+09

                                                 NTA
0  Crown Heights South                           ...
1  Morrisania-Melrose                            ...
2  West Concourse                                ...
3  Chinatown                                     ...
4  Pomonok-Flushing Heights-Hillcrest            ...

[5 rows x 64 columns]

sat_results

      DBN                                    SCHOOL NAME  \
0  01M292  HENRY STREET SCHOOL FOR INTERNATIONAL STUDIES
1  01M448            UNIVERSITY NEIGHBORHOOD HIGH SCHOOL
2  01M450                     EAST SIDE COMMUNITY SCHOOL
3  01M458                      FORSYTH SATELLITE ACADEMY
4  01M509                        MARTA VALLE HIGH SCHOOL

  Num of SAT Test Takers SAT Critical Reading Avg. Score SAT Math Avg. Score  \
0                     29                             355                 404
1                     91                             383                 423
2                     70                             377                 402
3                      7                             414                 401
4                     44                             390                 433

  SAT Writing Avg. Score
0                    363
1                    366
2                    370
3                    359
4                    384

### Reading in the Survey Data

1. Read in survey_all.txt.
    - Use the pandas.read_csv() function to read survey_all.txt into the variable all_survey. Recall that this file is located in the schools folder.
        - Specify the keyword argument delimiter="\t".
        - Specify the keyword argument encoding="windows-1252".
2. Read in survey_d75.txt.
    - Use the pandas.read_csv() function to read schools/survey_d75.txt into the variable d75_survey. Recall that this file is located in the schools folder.
        - Specify the keyword argument delimiter="\t".
        - Specify the keyword argument encoding="windows-1252".
3. Combine d75_survey and all_survey into a single dataframe.
    - Use the pandas concat() function with the keyword argument axis=0 to combine d75_survey and all_survey into the dataframe survey.
    - Pass in all_survey first, then d75_survey when calling the pandas.concat() function.
4. Display the first five rows of survey using the pandas.DataFrame.head() function.

In [16]:
all_survey = pd.read_csv("schools/survey_all.txt", encoding ='Windows-1252', delimiter='\t')
d75_survey = pd.read_csv("schools/survey_d75.txt", encoding ='Windows-1252', delimiter='\t')
survey = pd.concat([all_survey, d75_survey], axis=0)
survey.head()

/home/naveen/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  This is separate from the ipykernel package so we can avoid doing imports until

,N_p,N_s,N_t,aca_p_11,aca_s_11,aca_t_11,aca_tot_11,bn,com_p_11,com_s_11,...,t_q8c_1,t_q8c_2,t_q8c_3,t_q8c_4,t_q9,t_q9_1,t_q9_2,t_q9_3,t_q9_4,t_q9_5
0,90.0,NaN,22.0,7.8,NaN,7.9,7.9,M015,7.6,NaN,...,29.0,67.0,5.0,0.0,NaN,5.0,14.0,52.0,24.0,5.0
1,161.0,NaN,34.0,7.8,NaN,9.1,8.4,M019,7.6,NaN,...,74.0,21.0,6.0,0.0,NaN,3.0,6.0,3.0,78.0,9.0
2,367.0,NaN,42.0,8.6,NaN,7.5,8.0,M020,8.3,NaN,...,33.0,35.0,20.0,13.0,NaN,3.0,5.0,16.0,70.0,5.0
3,151.0,145.0,29.0,8.5,7.4,7.8,7.9,M034,8.2,5.9,...,21.0,45.0,28.0,7.0,NaN,0.0,18.0,32.0,39.0,11.0
4,90.0,NaN,23.0,7.9,NaN,8.1,8.0,M063,7.9,NaN,...,59.0,36.0,5.0,0.0,NaN,10.0,5.0,10.0,60.0,15.0

**Here, we'll need filter the columns to remove the ones we don't need. Luckily, there's a <a href="https://data.cityofnewyork.us/api/views/mnz3-dyi8/files/aa68d821-4dbb-4eb2-9448-3d8cbbad5044?download=true&filename=Survey%20Data%20Dictionary.xls">data dictionary</a> at the original data download <a href="https://data.cityofnewyork.us/Education/2010-2011-NYC-School-Survey/mnz3-dyi8">location</a>. The dictionary tells us what each column represents. Based on our knowledge of the problem and the analysis we're trying to do, we can use the data dictionary to determine which columns to use.<br><br>Based on the dictionary, it looks like these are the relevant columns:**

***[*** *"dbn", "rr_s", "rr_t", "rr_p", "N_s", "N_t", "N_p", "saf_p_11", "com_p_11", "eng_p_11", "aca_p_11", "saf_t_11", "com_t_11", "eng_t_11", "aca_t_11", "saf_s_11", "com_s_11", "eng_s_11", "aca_s_11", "saf_tot_11", "com_tot_11", "eng_tot_11", "aca_tot_11"* ***]***

### Cleaning up the Surveys


1. Copy the data from the dbn column of survey into a new column in survey called DBN.
2. Filter survey so it only contains the columns we listed above. You can do this using pandas.DataFrame.loc[].
    - Remember that we renamed dbn to DBN; be sure to change the list of columns we want to keep accordingly.
3. Assign the dataframe survey to the key survey in the dictionary data.
4. When you're finished, the value in data["survey"] should be a dataframe with 23 columns and 1702 rows.