# *Introduction To Pandas*

**Here, we will be working with data set from Fortune magazine's Global 500 list 2017, which ranks the top 500 corporations worldwide by revenue. The dataset (<a href="https://data.world/chasewillden/fortune-500-companies-2017">compiled here</a>) is a CSV file called f500.csv.**

### Data Dictionary:

> <font color=blue>***company***</font> - The Name of the company.<br>
> <font color=blue>***rank***</font> - The Global 500 rank for the company.<br>
> <font color=blue>***revenues***</font> - The company's total revenues for the fiscal year, in millions of dollars (USD).<br>
> <font color=blue>***revenue_change***</font> - The percentage change in revenue between the current and prior fiscal years.<br>
> <font color=blue>***profits***</font> - Net income for the fiscal year, in millions of dollars (USD).<br>
> <font color=blue>***ceo***</font> - The company's Chief Executive Officer.<br>
> <font color=blue>***industry***</font> - The industry in which the company operates.<br>
> <font color=blue>***sector***</font> - The sector in which the company operates.<br>
> <font color=blue>***previous_rank***</font> - The Global 500 rank for the company for the prior year.<br>
> <font color=blue>***country***</font> - The Country in which the company is headquartered.<br>
> <font color=blue>***hq_location***</font> - The City and Country, (or City and State for the USA) where the company is headquarted.<br>
> <font color=blue>***employees***</font> - Total employees (full-time equivalent, if available) at fiscal year-end.<br>

**We have modified the original data set into a more accessible format**

### Understanding Pandas and NumPy
1. Use Python's type() function to assign the type of f500 to f500_type.
2. Use the DataFrame.shape attribute to assign the shape of f500 to f500_shape.
3. After you have run your code, use the variable inspector to look at the variables f500, f500_type, and f500_shape.

In [2]:
import pandas as pd
f500 = pd.read_csv("f500.csv", index_col=0)
f500.index.name = None 

f500_type = type(f500)

f500_shape = f500.shape

f500

,rank,revenues,revenue_change,profits,assets,profit_change,ceo,industry,sector,previous_rank,country,hq_location,website,years_on_global_500_list,employees,total_stockholder_equity
Walmart,1,485873,0.8,13643.0,198825,-7.2,C. Douglas McMillon,General Merchandisers,Retailing,1,USA,"Bentonville, AR",http://www.walmart.com,23,2300000,77798
State Grid,2,315199,-4.4,9571.3,489838,-6.2,Kou Wei,Utilities,Energy,2,China,"Beijing, China",http://www.sgcc.com.cn,17,926067,209456
Sinopec Group,3,267518,-9.1,1257.9,310726,-65.0,Wang Yupu,Petroleum Refining,Energy,4,China,"Beijing, China",http://www.sinopec.com,19,713288,106523
China National Petroleum,4,262573,-12.3,1867.5,585619,-73.7,Zhang Jianhua,Petroleum Refining,Energy,3,China,"Beijing, China",http://www.cnpc.com.cn,17,1512048,301893
Toyota Motor,5,254694,7.7,16899.3,437575,-12.3,Akio Toyoda,Motor Vehicles and Parts,Motor Vehicles & Parts,8,Japan,"Toyota, Japan",http://www.toyota-global.com,23,364445,157210
Volkswagen,6,240264,1.5,5937.3,432116,NaN,Matthias Muller,Motor Vehicles and Parts,Motor Vehicles & Parts,7,Germany,"Wolfsburg, Germany",http://www.volkswagen.com,23,626715,97753
Royal Dutch Shell,7,240033,-11.8,4575.0,411275,135.9,Ben van Beurden,Petroleum Refining,Energy,5,Netherlands,"The Hague, Netherlands",http://www.shell.com,23,89000,186646
Berkshire Hathaway,8,223604,6.1,24074.0,620854,NaN,Warren E. Buffett,Insurance: Property and Casualty (Stock),Financials,11,USA,"Omaha, NE",http://www.berkshirehathaway.com,21,367700,283001
Apple,9,215639,-7.7,45687.0,321686,-14.4,Timothy D. Cook,"Computers, Office Equipment",Technology,9,USA,"Cupertino, CA",http://www.apple.com,15,116000,128249
Exxon Mobil,10,205004,-16.7,7840.0,330314,-51.5,Darren W. Woods,Petroleum Refining,Energy,6,USA,"Irving, TX",http://www.exxonmobil.com,23,72700,167325
McKesson,11,198533,3.1,5070.0,60969,124.5,John H. Hammergren,Wholesalers: Health Care,Wholesalers,12,USA,"San Francisco, CA",http://www.mckesson.com,23,64500,11095
BP,12,186606,-17.4,115.0,263316,NaN,Robert W. Dudley,Petroleum Refining,Energy,10,Britain,"London, Britain",http://www.bp.com,23,74500,95286
UnitedHealth Group,13,184840,17.7,7017.0,122810,20.7,Stephen J. Hemsley,Health Care: Insurance and Managed Care,Health Care,17,USA,"Minnetonka, MN",http://www.unitedhealthgroup.com,21,230000,38274
CVS Health,14,177526,15.8,5317.0,94462,1.5,Larry J. Merlo,Health Care: Pharmacy and Other Services,Health Care,18,USA,"Woonsocket, RI",http://www.cvshealth.com,22,204000,36830
Samsung Electronics,15,173957,-2.0,19316.5,217104,16.8,Oh-Hyun Kwon,"Electronics, Electrical Equip.",Technology,13,South Korea,"Suwon, South Korea",http://www.samsung.com,23,325000,154376
Glencore,16,173883,2.0,1379.0,124600,NaN,Ivan Glasenberg,"Mining, Crude-Oil Production",Energy,14,Switzerland,"Baar, Switzerland",http://www.glencore.com,7,93123,44243
Daimler,17,169483,2.2,9428.4,256262,0.9,Dieter Zetsche,Motor Vehicles and Parts,Motor Vehicles & Parts,16,Germany,"Stuttgart, Germany",http://www.daimler.com,23,282488,61116
General Motors,18,166380,9.2,9427.0,221690,-2.7,Mary T. Barra,Motor Vehicles and Parts,Motor Vehicles & Parts,20,USA,"Detroit, MI",http://www.gm.com,23,225000,43836
AT&T,19,163786,11.6,12976.0,403821,-2.8,Randall L. Stephenson,Telecommunications,Telecommunications,23,USA,"Dallas, TX",http://www.att.com,23,268540,123135
EXOR Group,20,154894,1.5,651.3,186172,-21.1,John Elkann,Diversified Financials,Financials,19,Netherlands,"Amsterdam, Netherlands",http://www.exor.com,7,302562,11582
Ford Motor,21,151800,1.5,4596.0,237951,-37.7,James P. Hackett,Motor Vehicles and Parts,Motor Vehicles & Parts,21,USA,"Dearborn, MI",http://www.ford.com,23,201000,29170
Industrial & Commercial Bank of China,22,147675,-11.7,41883.9,3473238,-5.0,Gu Shu,Banks: Commercial and Savings,Financials,15,China,"Beijing, China",http://www.icbc-ltd.com,19,461749,283438
AmerisourceBergen,23,146850,8.0,1427.9,33656,NaN,Steven H. Collis,Wholesalers: Health Care,Wholesalers,28,USA,"Chesterbrook, PA",http://www.amerisourcebergen.com,18,18500,2129
China State Construction Engineering,24,144505,3.1,2492.9,201269,10.7,Guan Qing,"Engineering, Construction",Engineering & Construction,27,China,"Beijing, China",http://www.cscec.com,6,263915,15344
AXA,25,143722,11.2,6446.0,941556,3.5,Thomas Buberl,"Insurance: Life, Health (stock)",Financials,33,France,"Paris, France",http://www.axa.com,23,97707,74454
Amazon.com,26,135987,27.1,2371.0,83402,297.8,Jeffrey P. Bezos,Internet Services and Retailing,Technology,44,USA,"Seattle, WA",http://www.amazon.com,9,341400,19285
Hon Hai Precision Industry,27,135129,-4.3,4608.8,80436,-0.4,Terry Gou,"Electronics, Electrical Equip.",Technology,25,Taiwan,"New Taipei City, Taiwan",http://www.foxconn.com,13,726772,33476
China Construction Bank,28,135093,-8.7,34840.9,3016578,-4.0,Wang Hongzhang,Banks: Commercial and Savings,Financials,22,China,"Beijing, China",http://www.ccb.com,18,362482,226851
Honda Motor,29,129198,6.2,5690.3,170165,98.3,Takahiro Hachigo,Motor Vehicles and Parts,Motor Vehicles & Parts,36,Japan,"Tokyo, Japan",http://www.honda.com,23,211915,65482
Total,30,127925,-10.8,6196.0,230978,21.8,Patrick Pouyanne,Petroleum Refining,Energy,24,France,"Courbevoie, France",http://www.total.com,23,102168,98680
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Amgen,471,22991,6.1,7722.0,77626,11.3,Robert A. Bradway,Pharmaceuticals,Health Care,487,USA,"Thousand Oaks, CA",http://www.amgen.com,2,19200,29875
Rabobank Group,472,22956,-4.4,828.3,698790,-15.1,Wiebe Draijer,Banks: Commercial and Savings,Financials,445,Netherlands,"Utrecht, Netherlands",http://www.rabobank.com,23,40029,27232
Altice,473,22953,42.2,-1722.5,84805,NaN,Michel Combes,Telecommunications,Telecommunications,0,Netherlands,"Amsterdam, Netherlands",http://www.altice.net,1,49732,-2668
Onex,474,22943,3.8,-130.0,42913,NaN,Gerald W. Schwartz,Semiconductors and Other Electronic Components,Technology,483,Canada,"Toronto, Ontario, Canada",http://www.onex.com,18,161000,-490
US Foods Holding,475,22919,-0.9,209.8,8945,25.2,Pietro Satriano,Wholesalers: Food and Grocery,Wholesalers,461,USA,"Rosemont, IL",http://www.usfoods.com,2,25000,2538
Shanxi Jincheng Anthracite Coal Mining Group,476,22875,-17.0,3.0,32954,NaN,He Tiancai,"Mining, Crude-Oil Production",Energy,384,China,"Jincheng, China",http://www.jamg.cn,5,135691,2988
Randstad Holding,477,22873,7.3,650.2,9624,13.0,Jacques van den Broek,Temporary Help,Business Services,494,Netherlands,"Diemen, Netherlands",http://www.randstad.com,5,32280,4366
Tencent Holdings,478,22871,39.7,6185.9,56968,35.0,Pony Ma,Internet Services and Retailing,Technology,0,China,"Shenzhen, China",http://www.tencent.com,1,38775,25128
LG Display,479,22840,-9.0,781.4,20606,-8.6,Sang-Beom Han,"Electronics, Electrical Equip.",Technology,429,South Korea,"Seoul, South Korea",http://www.lgdisplay.com,6,49094,10729
Emirates Group,480,22799,0.3,340.3,33096,-82.5,Sheikh Ahmed bin Saeed Al Maktoum,Airlines,Transportation,472,U.A.E,"Dubai, U.A.E",http://www.theemiratesgroup.com,2,64768,9395
U.S. Bancorp,481,22744,5.8,5888.0,445964,0.2,Andrew J. Cecere,Banks: Commercial and Savings,Financials,490,USA,"Minneapolis, MN",http://www.usbank.com,12,71191,47298
H & M Hennes & Mauritz,482,22618,4.6,2192.3,10681,-12.3,Karl-Johan Persson,Specialty Retailers,Retailing,488,Sweden,"Stockholm, Sweden",http://www.hm.com,2,114586,6635
Aflac,483,22559,8.1,2659.0,129819,5.0,Daniel P. Amos,"Insurance: Life, Health (stock)",Financials,0,USA,"Columbus, GA",http://www.aflac.com,10,10212,20482
Sodexo,484,22477,-2.0,707.2,15766,-12.7,Michel Landel,Food Services,"Hotels, Restaurants & Leisure",466,France,"Issy-les-Moulineaux, France",http://www.sodexo.com,18,425594,4085
Suning Commerce Group,485,22366,3.7,106.0,19738,-23.6,Ren Jun,Specialty Retailers,Retailing,0,China,"Nanjing, China",http://www.suning.com,1,60354,9455
GS Caltex,486,22207,-11.4,1221.1,15969,42.1,Jin-Soo Huh,Petroleum Refining,Energy,431,South Korea,"Seoul, South Korea",http://www.gscaltex.com,6,2949,8150
Ultrapar Holdings,487,22167,-2.3,447.5,7426,-0.8,Thilo Mannhardt,Energy,Energy,474,Brazil,"Sao Paulo, Brazil",http://www.ultra.com.br,8,15173,2621
Xiamen C&D,488,22145,6.6,280.2,21729,15.6,Huang Wenzhou,Trading,Wholesalers,0,China,"Xiamen, China",http://www.chinacdc.com,1,18381,3985
Sears Holdings,489,22138,-12.0,-2221.0,9362,NaN,Edward S. Lampert,General Merchandisers,Retailing,425,USA,"Hoffman Estates, IL",http://www.searsholdings.com,23,140000,-3824
China General Technology,490,22113,-20.1,413.6,20860,-20.8,Xu Xianping,"Engineering, Construction",Engineering & Construction,383,China,"Beijing, China",http://www.genertec.com.cn,4,38589,5114
National Grid,491,22036,-3.2,10150.6,82310,160.2,John Pettigrew,Utilities,Energy,471,Britain,"London, Britain",http://www.nationalgrid.com,12,22132,25463
Dollar General,492,21987,7.9,1251.1,11672,7.4,Todd J. Vasos,Specialty Retailers,Retailing,0,USA,"Goodlettsville, TN",http://www.dollargeneral.com,1,121000,5406
Telecom Italia,493,21941,-17.4,1999.4,74295,NaN,Flavio Cattaneo,Telecommunications,Telecommunications,404,Italy,"Milan, Italy",http://www.telecomitalia.com,18,61227,22366
Xiamen ITG Holding Group,494,21930,34.3,35.6,12161,-25.1,Xu Xiaoxi,Trading,Wholesalers,0,China,"Xiamen, China",http://www.itgholding.com.cn,1,18454,1066
Xinjiang Guanghui Industry Investment,495,21919,31.1,251.8,31957,49.9,Shang Jiqiang,Trading,Wholesalers,0,China,"Urumqi, China",http://www.guanghui.com,1,65616,4563
Teva Pharmaceutical Industries,496,21903,11.5,329.0,92890,-79.3,Yitzhak Peterburg,Pharmaceuticals,Health Care,0,Israel,"Petach Tikva, Israel",http://www.tevapharm.com,1,56960,33337
New China Life Insurance,497,21796,-13.3,743.9,100609,-45.6,Wan Feng,"Insurance: Life, Health (stock)",Financials,427,China,"Beijing, China",http://www.newchinalife.com,2,54378,8507
Wm. Morrison Supermarkets,498,21741,-11.3,406.4,11630,20.4,David T. Potts,Food and Drug Stores,Food & Drug Stores,437,Britain,"Bradford, Britain",http://www.morrisons.com,13,77210,5111
TUI,499,21655,-5.5,1151.7,16247,195.5,Friedrich Joussen,Travel Services,Business Services,467,Germany,"Hanover, Germany",http://www.tuigroup.com,23,66779,3006
AutoNation,500,21609,3.6,430.5,10060,-2.7,Michael J. Jackson,Specialty Retailers,Retailing,0,USA,"Fort Lauderdale, FL",http://www.autonation.com,12,26000,2310

### Introducing DataFrames

1. Using the links above to the documentation if you need to, use the three methods we just learned about to learn more about the f500 dataframe:
    - Use the head() method to select the first 6 rows and assign the result to f500_head.
    - Use the tail() method to select the last 8 rows and assign the result to f500_tail.
    - Use the info() method to display information about the dataframe.
2. After you have run your code, use the variable inspector and output to view information about the dataframe.

In [3]:
f500_head = f500.head(6)
f500_tail = f500.tail(8)
print(f500.info())

<class 'pandas.core.frame.DataFrame'>
Index: 500 entries, Walmart to AutoNation
Data columns (total 16 columns):
rank                        500 non-null int64
revenues                    500 non-null int64
revenue_change              498 non-null float64
profits                     499 non-null float64
assets                      500 non-null int64
profit_change               436 non-null float64
ceo                         500 non-null object
industry                    500 non-null object
sector                      500 non-null object
previous_rank               500 non-null int64
country                     500 non-null object
hq_location                 500 non-null object
website                     500 non-null object
years_on_global_500_list    500 non-null int64
employees                   500 non-null int64
total_stockholder_equity    500 non-null int64
dtypes: float64(3), int64(7), object(6)
memory usage: 66.4+ KB
None

### Selecting Columns From a DataFrame By Label
1. Select the industry column, and assign the result to the variable name industries.
2. Select the rank, previous_rank and years_on_global_500_list columns, in order, and assign the result to the variable name previous.
3. Select all columns from revenues up to and including profit_change, in order, and assign the result to the variable name financial_data.

In [4]:
industries = f500["industry"]
previous = f500[["rank", "previous_rank", "years_on_global_500_list"]]
financial_data = f500.loc[:,"revenues":"profit_change"]
financial_data

,revenues,revenue_change,profits,assets,profit_change
Walmart,485873,0.8,13643.0,198825,-7.2
State Grid,315199,-4.4,9571.3,489838,-6.2
Sinopec Group,267518,-9.1,1257.9,310726,-65.0
China National Petroleum,262573,-12.3,1867.5,585619,-73.7
Toyota Motor,254694,7.7,16899.3,437575,-12.3
Volkswagen,240264,1.5,5937.3,432116,NaN
Royal Dutch Shell,240033,-11.8,4575.0,411275,135.9
Berkshire Hathaway,223604,6.1,24074.0,620854,NaN
Apple,215639,-7.7,45687.0,321686,-14.4
Exxon Mobil,205004,-16.7,7840.0,330314,-51.5
McKesson,198533,3.1,5070.0,60969,124.5
BP,186606,-17.4,115.0,263316,NaN
UnitedHealth Group,184840,17.7,7017.0,122810,20.7
CVS Health,177526,15.8,5317.0,94462,1.5
Samsung Electronics,173957,-2.0,19316.5,217104,16.8
Glencore,173883,2.0,1379.0,124600,NaN
Daimler,169483,2.2,9428.4,256262,0.9
General Motors,166380,9.2,9427.0,221690,-2.7
AT&T,163786,11.6,12976.0,403821,-2.8
EXOR Group,154894,1.5,651.3,186172,-21.1
Ford Motor,151800,1.5,4596.0,237951,-37.7
Industrial & Commercial Bank of China,147675,-11.7,41883.9,3473238,-5.0
AmerisourceBergen,146850,8.0,1427.9,33656,NaN
China State Construction Engineering,144505,3.1,2492.9,201269,10.7
AXA,143722,11.2,6446.0,941556,3.5
Amazon.com,135987,27.1,2371.0,83402,297.8
Hon Hai Precision Industry,135129,-4.3,4608.8,80436,-0.4
China Construction Bank,135093,-8.7,34840.9,3016578,-4.0
Honda Motor,129198,6.2,5690.3,170165,98.3
Total,127925,-10.8,6196.0,230978,21.8
...,...,...,...,...,...
Amgen,22991,6.1,7722.0,77626,11.3
Rabobank Group,22956,-4.4,828.3,698790,-15.1
Altice,22953,42.2,-1722.5,84805,NaN
Onex,22943,3.8,-130.0,42913,NaN
US Foods Holding,22919,-0.9,209.8,8945,25.2
Shanxi Jincheng Anthracite Coal Mining Group,22875,-17.0,3.0,32954,NaN
Randstad Holding,22873,7.3,650.2,9624,13.0
Tencent Holdings,22871,39.7,6185.9,56968,35.0
LG Display,22840,-9.0,781.4,20606,-8.6
Emirates Group,22799,0.3,340.3,33096,-82.5
U.S. Bancorp,22744,5.8,5888.0,445964,0.2
H & M Hennes & Mauritz,22618,4.6,2192.3,10681,-12.3
Aflac,22559,8.1,2659.0,129819,5.0
Sodexo,22477,-2.0,707.2,15766,-12.7
Suning Commerce Group,22366,3.7,106.0,19738,-23.6
GS Caltex,22207,-11.4,1221.1,15969,42.1
Ultrapar Holdings,22167,-2.3,447.5,7426,-0.8
Xiamen C&D,22145,6.6,280.2,21729,15.6
Sears Holdings,22138,-12.0,-2221.0,9362,NaN
China General Technology,22113,-20.1,413.6,20860,-20.8
National Grid,22036,-3.2,10150.6,82310,160.2
Dollar General,21987,7.9,1251.1,11672,7.4
Telecom Italia,21941,-17.4,1999.4,74295,NaN
Xiamen ITG Holding Group,21930,34.3,35.6,12161,-25.1
Xinjiang Guanghui Industry Investment,21919,31.1,251.8,31957,49.9
Teva Pharmaceutical Industries,21903,11.5,329.0,92890,-79.3
New China Life Insurance,21796,-13.3,743.9,100609,-45.6
Wm. Morrison Supermarkets,21741,-11.3,406.4,11630,20.4
TUI,21655,-5.5,1151.7,16247,195.5
AutoNation,21609,3.6,430.5,10060,-2.7

### Column Selection Shortcuts

1. Select the country column, and assign the result to the variable name countries.
2. Select the revenues and years_on_global_500_list columns, in order, and assign the result to the variable name revenues_years.
3. Select all columns from ceo up to and including sector, in order, and assign the result to the variable name ceo_to_sector.

In [5]:
countries = f500["country"]
revenues_years = f500[["revenues", "years_on_global_500_list"]]
ceo_to_sector = f500.loc[:, "ceo":"sector"]

revenues_years

,revenues,years_on_global_500_list
Walmart,485873,23
State Grid,315199,17
Sinopec Group,267518,19
China National Petroleum,262573,17
Toyota Motor,254694,23
Volkswagen,240264,23
Royal Dutch Shell,240033,23
Berkshire Hathaway,223604,21
Apple,215639,15
Exxon Mobil,205004,23
McKesson,198533,23
BP,186606,23
UnitedHealth Group,184840,21
CVS Health,177526,22
Samsung Electronics,173957,23
Glencore,173883,7
Daimler,169483,23
General Motors,166380,23
AT&T,163786,23
EXOR Group,154894,7
Ford Motor,151800,23
Industrial & Commercial Bank of China,147675,19
AmerisourceBergen,146850,18
China State Construction Engineering,144505,6
AXA,143722,23
Amazon.com,135987,9
Hon Hai Precision Industry,135129,13
China Construction Bank,135093,18
Honda Motor,129198,23
Total,127925,23
...,...,...
Amgen,22991,2
Rabobank Group,22956,23
Altice,22953,1
Onex,22943,18
US Foods Holding,22919,2
Shanxi Jincheng Anthracite Coal Mining Group,22875,5
Randstad Holding,22873,5
Tencent Holdings,22871,1
LG Display,22840,6
Emirates Group,22799,2
U.S. Bancorp,22744,12
H & M Hennes & Mauritz,22618,2
Aflac,22559,10
Sodexo,22477,18
Suning Commerce Group,22366,1
GS Caltex,22207,6
Ultrapar Holdings,22167,8
Xiamen C&D,22145,1
Sears Holdings,22138,23
China General Technology,22113,4
National Grid,22036,12
Dollar General,21987,1
Telecom Italia,21941,18
Xiamen ITG Holding Group,21930,1
Xinjiang Guanghui Industry Investment,21919,1
Teva Pharmaceutical Industries,21903,1
New China Life Insurance,21796,2
Wm. Morrison Supermarkets,21741,13
TUI,21655,23
AutoNation,21609,12

### Selecting Items from a Series By Label

1. From the pandas series ceos:
    - Select the item at index label Walmart and assign the result to the variable name walmart.
    - Select the items from index label Apple up to and including index label Samsung Electronics and assign the result to the variable name apple_to_samsung.
    - Select the items with index labels Exxon Mobil, BP, and Chevron, in order, and assign the result to the variable name oil_companies.

In [6]:
ceos = f500["ceo"]
walmart = ceos["Walmart"]
apple_to_samsung = ceos["Apple":"Samsung Electronics"]
oil_companies = ceos[["Exxon Mobil", "BP", "Chevron"]]

ceos

Walmart                                                       C. Douglas McMillon
State Grid                                                                Kou Wei
Sinopec Group                                                           Wang Yupu
China National Petroleum                                            Zhang Jianhua
Toyota Motor                                                          Akio Toyoda
Volkswagen                                                        Matthias Muller
Royal Dutch Shell                                                 Ben van Beurden
Berkshire Hathaway                                              Warren E. Buffett
Apple                                                             Timothy D. Cook
Exxon Mobil                                                       Darren W. Woods
McKesson                                                       John H. Hammergren
BP                                                               Robert W. Dudley
UnitedHealth Group                                             Stephen J. Hemsley
CVS Health                                                         Larry J. Merlo
Samsung Electronics                                                  Oh-Hyun Kwon
Glencore                                                          Ivan Glasenberg
Daimler                                                            Dieter Zetsche
General Motors                                                      Mary T. Barra
AT&T                                                        Randall L. Stephenson
EXOR Group                                                            John Elkann
Ford Motor                                                       James P. Hackett
Industrial & Commercial Bank of China                                      Gu Shu
AmerisourceBergen                                                Steven H. Collis
China State Construction Engineering                                    Guan Qing
AXA                                                                 Thomas Buberl
Amazon.com                                                       Jeffrey P. Bezos
Hon Hai Precision Industry                                              Terry Gou
China Construction Bank                                            Wang Hongzhang
Honda Motor                                                      Takahiro Hachigo
Total                                                            Patrick Pouyanne
                                                              ...
Amgen                                                           Robert A. Bradway
Rabobank Group                                                      Wiebe Draijer
Altice                                                              Michel Combes
Onex                                                           Gerald W. Schwartz
US Foods Holding                                                  Pietro Satriano
Shanxi Jincheng Anthracite Coal Mining Group                           He Tiancai
Randstad Holding                                            Jacques van den Broek
Tencent Holdings                                                          Pony Ma
LG Display                                                          Sang-Beom Han
Emirates Group                                  Sheikh Ahmed bin Saeed Al Maktoum
U.S. Bancorp                                                     Andrew J. Cecere
H & M Hennes & Mauritz                                         Karl-Johan Persson
Aflac                                                              Daniel P. Amos
Sodexo                                                              Michel Landel
Suning Commerce Group                                                     Ren Jun
GS Caltex                                                             Jin-Soo Huh
Ultrapar Holdings                                                 Thilo Mannhardt
Xiamen C&D                                                          Huang Wenzhou
Sears Holdings                                                  Edward S. Lampert
China General Technology                                              Xu Xianping
National Grid                                                      John Pettigrew
Dollar General                                                      Todd J. Vasos
Telecom Italia                                                    Flavio Cattaneo
Xiamen ITG Holding Group                                                Xu Xiaoxi
Xinjiang Guanghui Industry Investment                               Shang Jiqiang
Teva Pharmaceutical Industries                                  Yitzhak Peterburg
New China Life Insurance                                                 Wan Feng
Wm. Morrison Supermarkets                                          David T. Potts
TUI                                                             Friedrich Joussen
AutoNation                                                     Michael J. Jackson
Name: ceo, Length: 500, dtype: object

### Selecting Rows From a DataFrame by Label

1. By selecting data from f500:
    - Create a new variable, drink_companies, with:
        - Rows with indicies Anheuser-Busch InBev, Coca-Cola, and Heineken Holding, in that order.
        - All columns.
    - Create a new variable big_movers, with:
        - Rows with indicies Aviva, HP, JD.com, and BHP Billiton, in that order.
        - The rank and previous_rank columns, in that order.
    - Create a new variable, middle_companies with:
        - All rows with indicies from Tata Motorsto Nationwide, inclusive.
        - All columns from rank to country, inclusive.

In [7]:
drink_companies = f500.loc[["Anheuser-Busch InBev", "Coca-Cola", "Heineken Holding"], :]
big_movers = f500.loc[["Aviva", "HP", "JD.com", "BHP Billiton"], ["rank", "previous_rank"]]
middle_companies = f500.loc["Tata Motors":"Nationwide", "rank":"country"]

big_movers

              rank  previous_rank
Aviva           90            279
HP             194             48
JD.com         261            366
BHP Billiton   350            168

### Series and DataFrame Describe Methods
1. Use the appropriate describe() method to:
    - Return a series of descriptive statistics for the profits column, and assign the result to profits_desc.
    - Return a dataframe of descriptive statistics for the revenues and employees columns, in order, and assign the result to revenue_and_employees_desc.
    - Return a dataframe of descriptive statistics for every column in the f500 dataframe, by checking the documentation for the correct value for the include parameter, and assign the result to all_desc.

In [8]:
profits_desc = f500["profits"].describe()
revenue_and_employees_desc = f500[["revenues", "employees"]].describe()
all_desc = f500.describe(include = 'all')

all_desc

,rank,revenues,revenue_change,profits,assets,profit_change,ceo,industry,sector,previous_rank,country,hq_location,website,years_on_global_500_list,employees,total_stockholder_equity
count,500.000000,500.000000,498.000000,499.000000,5.000000e+02,436.000000,500,500,500,500.000000,500,500,500,500.000000,5.000000e+02,500.000000
unique,NaN,NaN,NaN,NaN,NaN,NaN,500,58,21,NaN,34,235,500,NaN,NaN,NaN
top,NaN,NaN,NaN,NaN,NaN,NaN,Alistair Phillips-Davies,Banks: Commercial and Savings,Financials,NaN,USA,"Beijing, China",http://www.onex.com,NaN,NaN,NaN
freq,NaN,NaN,NaN,NaN,NaN,NaN,1,51,118,NaN,132,56,1,NaN,NaN,NaN
mean,250.500000,55416.358000,4.538353,3055.203206,2.436323e+05,24.152752,NaN,NaN,NaN,222.134000,NaN,NaN,NaN,15.036000,1.339983e+05,30628.076000
std,144.481833,45725.478963,28.549067,5171.981071,4.851937e+05,437.509566,NaN,NaN,NaN,146.941961,NaN,NaN,NaN,7.932752,1.700878e+05,43642.576833
min,1.000000,21609.000000,-67.300000,-13038.000000,3.717000e+03,-793.700000,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,1.000000,3.280000e+02,-59909.000000
25%,125.750000,29003.000000,-5.900000,556.950000,3.658850e+04,-22.775000,NaN,NaN,NaN,92.750000,NaN,NaN,NaN,7.000000,4.293250e+04,7553.750000
50%,250.500000,40236.000000,0.550000,1761.600000,7.326150e+04,-0.350000,NaN,NaN,NaN,219.500000,NaN,NaN,NaN,17.000000,9.291050e+04,15809.500000
75%,375.250000,63926.750000,6.975000,3954.000000,1.805640e+05,17.700000,NaN,NaN,NaN,347.250000,NaN,NaN,NaN,23.000000,1.689172e+05,37828.500000
max,500.000000,485873.000000,442.300000,45687.000000,3.473238e+06,8909.500000,NaN,NaN,NaN,500.000000,NaN,NaN,NaN,23.000000,2.300000e+06,301893.000000

### More Data Exploratrion Methods

1. Use Series.value_counts() and Series.head() to return the 5 most common values for the country column, and assign the results to top5_countries.
2. Use Series.value_counts() and Series.head() to return the 5 most common values for the previous rank column, and assign the results to top5_previous_rank.
3. Use the appropriate max() method to find the maximum value for only the numeric columns from f500 (you may need to check the documentation), and assign the result to the variable max_f500.
4. After you have run your code, use the variable inspector to view each of the new variables you created.

In [9]:
top5_countries = f500["country"].value_counts().head()
top5_previous_rank = f500["previous_rank"].value_counts().head()
max_f500 = f500.max(numeric_only = True)

top5_countries

USA        132
China      109
Japan       51
Germany     29
France      29
Name: country, dtype: int64

### Assignment with Pandas
1. Add a new column, revenues_b to the f500 dataframe by using vectorized division to divide the values in the existing revenues column by 1000 (converting them from millions to billions).
2. The company 'Dow Chemical' have named a new CEO. Update the value where the index label is Dow Chemical and for the ceo column to Jim Fitterling.

In [10]:
f500["revenues_b"] =  f500["revenues"]/1000
f500.loc["Dow Chemical", "ceo"] = "Jim Fitterling"

f500["revenues_b"]

Walmart                                         485.873
State Grid                                      315.199
Sinopec Group                                   267.518
China National Petroleum                        262.573
Toyota Motor                                    254.694
Volkswagen                                      240.264
Royal Dutch Shell                               240.033
Berkshire Hathaway                              223.604
Apple                                           215.639
Exxon Mobil                                     205.004
McKesson                                        198.533
BP                                              186.606
UnitedHealth Group                              184.840
CVS Health                                      177.526
Samsung Electronics                             173.957
Glencore                                        173.883
Daimler                                         169.483
General Motors                                  166.380
AT&T                                            163.786
EXOR Group                                      154.894
Ford Motor                                      151.800
Industrial & Commercial Bank of China           147.675
AmerisourceBergen                               146.850
China State Construction Engineering            144.505
AXA                                             143.722
Amazon.com                                      135.987
Hon Hai Precision Industry                      135.129
China Construction Bank                         135.093
Honda Motor                                     129.198
Total                                           127.925
                                                 ...
Amgen                                            22.991
Rabobank Group                                   22.956
Altice                                           22.953
Onex                                             22.943
US Foods Holding                                 22.919
Shanxi Jincheng Anthracite Coal Mining Group     22.875
Randstad Holding                                 22.873
Tencent Holdings                                 22.871
LG Display                                       22.840
Emirates Group                                   22.799
U.S. Bancorp                                     22.744
H & M Hennes & Mauritz                           22.618
Aflac                                            22.559
Sodexo                                           22.477
Suning Commerce Group                            22.366
GS Caltex                                        22.207
Ultrapar Holdings                                22.167
Xiamen C&D                                       22.145
Sears Holdings                                   22.138
China General Technology                         22.113
National Grid                                    22.036
Dollar General                                   21.987
Telecom Italia                                   21.941
Xiamen ITG Holding Group                         21.930
Xinjiang Guanghui Industry Investment            21.919
Teva Pharmaceutical Industries                   21.903
New China Life Insurance                         21.796
Wm. Morrison Supermarkets                        21.741
TUI                                              21.655
AutoNation                                       21.609
Name: revenues_b, Length: 500, dtype: float64

### Using Boolean Indexing with Pandas Objects
1. Create a boolean series, kr_bool, that compares whether the values in the country column from the f500 dataframe are equal to "South Korea"
2. Use that boolean series to index the full f500 dataframe, assigning just the first five rows to top_5_kr.

In [11]:
kr_bool = f500["country"] == "South Korea"
top_5_kr = f500[kr_bool].head()

top_5_kr

,rank,revenues,revenue_change,profits,assets,profit_change,ceo,industry,sector,previous_rank,country,hq_location,website,years_on_global_500_list,employees,total_stockholder_equity,revenues_b
Samsung Electronics,15,173957,-2.0,19316.5,217104,16.8,Oh-Hyun Kwon,"Electronics, Electrical Equip.",Technology,13,South Korea,"Suwon, South Korea",http://www.samsung.com,23,325000,154376,173.957
Hyundai Motor,78,80701,-0.8,4659.0,148092,-17.9,Mong-Koo Chung,Motor Vehicles and Parts,Motor Vehicles & Parts,84,South Korea,"Seoul, South Korea",http://worldwide.hyundai.com,22,129315,55639,80.701
SK Holdings,95,72579,107.4,659.7,85332,-86.0,Tae Won Chey,Petroleum Refining,Energy,294,South Korea,"Seoul, South Korea",http://www.sk.co.kr,2,84000,10858,72.579
Korea Electric Power,177,51500,-0.6,6074.1,147265,-48.3,Hwan-Eik Cho,Utilities,Energy,172,South Korea,"Jeollanam-do, South Korea",http://www.kepco.co.kr,23,43688,59394,51.500
LG Electronics,201,47712,-4.6,66.2,31348,-39.8,Seong-Jin Jo,"Electronics, Electrical Equip.",Technology,180,South Korea,"Seoul, South Korea",http://www.lg.com,17,75000,9926,47.712

### Using Boolean Arrays to Assign Values
1. Use boolean indexing to update values in the previous_rank column of the f500 dataframe:
    - Where previous there was a value of 0, there should now be a value of np.nan.
    - It is up to you whether you assign the boolean series to its own variable first, or whether you complete the operation in one line.
2. Create a new pandas series, prev_rank_after, using the same syntax that was used to create the prev_rank_before series.
3. After you have run your code, use the variable inspector to compare prev_rank_before and prev_rank_after.

In [12]:
import numpy as np
prev_rank_before = f500["previous_rank"].value_counts(dropna=False).head()

f500.loc[f500['previous_rank'] == 0, "previous_rank"] = np.nan

prev_rank_after = f500["previous_rank"].value_counts(dropna=False).head()

prev_rank_after

NaN       33
 471.0     1
 234.0     1
 125.0     1
 166.0     1
Name: previous_rank, dtype: int64

### Challenge Top Performers By Country
1. Create a series, cities_usa, containing counts of the five most common Headquarter Location cities for companies headquartered in the USA.
2. Create a series, sector_china, containing counts of the three most common sectors for companies headquartered in the China.
3. Create float object, mean_employees_japan, containing the mean average number of employees for companies headquartered in Japan

In [13]:
top_3_countries = f500["country"].value_counts().head(3)

cities_usa = f500.loc[f500["country"] == "USA", "hq_location"].value_counts()
sector_china = f500.loc[f500["country"] == "China", "sector"].value_counts().head(3)

mean_employees_japan = f500.loc[f500["country"] == "Japan", "employees"].mean()

#companies_china = f500[f500["country"] == "China"]
#financial_china = companies_china[companies_china["sector"] = "Financials"]
#print(financial_china)

sector_financial = f500[f500["sector"] == "Financials"]
# print(sector_financial)

companies_china = sector_financial[sector_financial["country"] == "China"]

companies_china

,rank,revenues,revenue_change,profits,assets,profit_change,ceo,industry,sector,previous_rank,country,hq_location,website,years_on_global_500_list,employees,total_stockholder_equity,revenues_b
Industrial & Commercial Bank of China,22,147675,-11.7,41883.9,3473238,-5.0,Gu Shu,Banks: Commercial and Savings,Financials,15.0,China,"Beijing, China",http://www.icbc-ltd.com,19,461749,283438,147.675
China Construction Bank,28,135093,-8.7,34840.9,3016578,-4.0,Wang Hongzhang,Banks: Commercial and Savings,Financials,22.0,China,"Beijing, China",http://www.ccb.com,18,362482,226851,135.093
Agricultural Bank of China,38,117275,-12.1,27687.8,2816039,-3.6,Zhao Huan,Banks: Commercial and Savings,Financials,29.0,China,"Beijing, China",http://www.abchina.com,18,501368,189682,117.275
Ping An Insurance,39,116581,5.7,9392.0,802490,8.9,Ma Mingzhe,"Insurance: Life, Health (stock)",Financials,41.0,China,"Shenzhen, China",http://www.pingan.com,8,318588,55177,116.581
Bank of China,42,113708,-7.1,24773.4,2611539,-8.9,Chen Siqing,Banks: Commercial and Savings,Financials,35.0,China,"Beijing, China",http://www.boc.cn,23,308900,203134,113.708
China Life Insurance,51,104818,3.5,162.4,483026,-96.1,Yang Mingsheng,"Insurance: Life, Health (stock)",Financials,54.0,China,"Beijing, China",http://www.chinalife.com.cn,15,143676,14079,104.818
People’s Insurance Co. of China,114,66732,3.3,2144.3,134132,-31.0,Wu Yan,Insurance: Property and Casualty (Stock),Financials,119.0,China,"Beijing, China",http://www.picc.com.cn,8,188570,18145,66.732
Anbang Insurance Group,139,60800,124.0,3883.9,430040,0.9,Wu Xiaohui,"Insurance: Life, Health (Mutual)",Financials,NaN,China,"Beijing, China",http://www.anbanggroup.com,1,40707,20372,60.800
Bank of Communications,171,52990,-7.1,10116.9,1209176,-4.4,Niu Ximing,Banks: Commercial and Savings,Financials,153.0,China,"Shanghai, China",http://www.bankcomm.com,9,95160,90531,52.990
CITIC Group,172,52852,-5.5,3236.3,938261,-14.0,Chang Zhenming,Diversified Financials,Financials,156.0,China,"Beijing, China",http://www.citicgroup.com.cn,9,201263,41784,52.852
China Merchants Bank,216,44552,-8.1,9344.8,855070,1.8,Tian Huiyu,Banks: Commercial and Savings,Financials,189.0,China,"Shenzhen, China",http://www.cmbchina.com,6,70461,57896,44.552
Industrial Bank,230,42622,-8.2,8105.9,875731,1.5,Tao Yiping,Banks: Commercial and Savings,Financials,195.0,China,"Fuzhou, China",http://www.cib.com.cn,5,56236,50382,42.622
Shanghai Pudong Development Bank,245,40689,-3.2,7992.8,842832,-0.7,Gao Guofu,Banks: Commercial and Savings,Financials,227.0,China,"Shanghai, China",http://www.spdb.com.cn,5,52832,52946,40.689
China Minsheng Banking,251,40234,-5.2,7201.6,848389,-1.8,Zheng Wanchun,Banks: Commercial and Savings,Financials,221.0,China,"Beijing, China",http://www.cmbc.com.cn,5,58720,49297,40.234
China Pacific Insurance (Group),252,40193,2.2,1814.9,146873,-35.7,Huo Lianhong,"Insurance: Life, Health (stock)",Financials,251.0,China,"Shanghai, China",http://www.cpic.com.cn,7,97032,18960,40.193
Greenland Holding Group,277,37240,12.8,1085.2,105495,-1.0,Zhang Yuliang,Real estate,Financials,311.0,China,"Shanghai, China",http://www.ldjt.com.cn,6,39887,8333,37.240
China Vanke,307,34458,17.5,3164.5,119555,9.8,Yu Liang,Real estate,Financials,356.0,China,"Shenzhen, China",http://www.vanke.com,2,58280,16324,34.458
China Everbright Group,329,32461,-1.3,1877.8,627701,-11.2,Tang Shuangning,Banks: Commercial and Savings,Financials,313.0,China,"Beijing, China",http://www.ebchina.com,3,61400,15661,32.461
China Evergrande Group,338,31828,50.2,2368.8,194384,-4.3,Hui Kayan,Real estate,Financials,496.0,China,"Guangzhou, China",http://www.evergrande.com,2,89250,22618,31.828
China Poly Group,341,31508,18.1,744.1,95657,-11.4,Zhang Zhengao,Real estate,Financials,401.0,China,"Beijing, China",http://www.poly.com.cn,3,76425,7676,31.508
Dalian Wanda Group,380,28483,4.0,110.3,152701,-95.5,Wang Jianlin,Real estate,Financials,385.0,China,"Beijing, China",http://www.wanda-group.com,2,155905,17237,28.483
AIA Group,383,28196,21.1,4164.0,185074,54.7,Ng Keng Hooi,"Insurance: Life, Health (stock)",Financials,456.0,China,"Hong Kong, China",http://www.aia.com,3,20000,34984,28.196
Yango Financial Holding,459,23657,11.5,159.2,24231,-59.0,Lin Tengjiao,Diversified Financials,Financials,NaN,China,"Fuzhou, China",http://www.yangofinance.com,1,10234,1925,23.657
Country Garden Holdings,467,23044,27.9,1733.6,85124,17.4,Mo Bin,Real estate,Financials,NaN,China,"Foshan, China",http://www.countrygarden.com.cn,1,94450,10091,23.044
New China Life Insurance,497,21796,-13.3,743.9,100609,-45.6,Wan Feng,"Insurance: Life, Health (stock)",Financials,427.0,China,"Beijing, China",http://www.newchinalife.com,2,54378,8507,21.796

# *Exploring Data with Pandas*

### Using iloc to Select by Integer Position

**We have provided code to read the f500.csv file into a dataframe and assigned it to f500, and inserted NaN values into the previous_rank column as we did in the previous mission.**

1. Select just the fifth row of the f500 dataframe, assigning the result to fifth_row.
2. Select the first three rows of the f500 dataframe, assigning the result to first_three_rows.
3. Select the first and seventh rows and the first 5 columns of the f500 dataframe, assigning the result to first_seventh_row_slice
4. After you have run your code, use the variable inspector to examine each of the objects you created.

In [14]:
fifth_row = f500.iloc[4]
first_three_rows = f500[:3]
first_seventh_row_slice = f500.iloc[[0, 6], :5]

fifth_row

rank                                                   5
revenues                                          254694
revenue_change                                       7.7
profits                                          16899.3
assets                                            437575
profit_change                                      -12.3
ceo                                          Akio Toyoda
industry                        Motor Vehicles and Parts
sector                            Motor Vehicles & Parts
previous_rank                                          8
country                                            Japan
hq_location                                Toyota, Japan
website                     http://www.toyota-global.com
years_on_global_500_list                              23
employees                                         364445
total_stockholder_equity                          157210
revenues_b                                       254.694
Name: Toyota Motor, dtype: object

### Reading CSV files with pandas

**The pandas library is already imported from the previous screen.**

1. Use the pandas.read_csv() function to read the f500.csv CSV file as a pandas dataframe, and assign it to the variable name f500.
    - Do not use the index_col parameter, so that the dataframe has integer index labels.
2. Use the code below to insert the NaN values into the previous_rank column: f500.loc[f500["previous_rank"] == 0, "previous_rank"] = np.nan

In [15]:
f500 = pd.read_csv("f500.csv")
f500.loc[f500["previous_rank"] == 0, "previous_rank"] = np.nan

f500.head()

,company,rank,revenues,revenue_change,profits,assets,profit_change,ceo,industry,sector,previous_rank,country,hq_location,website,years_on_global_500_list,employees,total_stockholder_equity
0,Walmart,1,485873,0.8,13643.0,198825,-7.2,C. Douglas McMillon,General Merchandisers,Retailing,1.0,USA,"Bentonville, AR",http://www.walmart.com,23,2300000,77798
1,State Grid,2,315199,-4.4,9571.3,489838,-6.2,Kou Wei,Utilities,Energy,2.0,China,"Beijing, China",http://www.sgcc.com.cn,17,926067,209456
2,Sinopec Group,3,267518,-9.1,1257.9,310726,-65.0,Wang Yupu,Petroleum Refining,Energy,4.0,China,"Beijing, China",http://www.sinopec.com,19,713288,106523
3,China National Petroleum,4,262573,-12.3,1867.5,585619,-73.7,Zhang Jianhua,Petroleum Refining,Energy,3.0,China,"Beijing, China",http://www.cnpc.com.cn,17,1512048,301893
4,Toyota Motor,5,254694,7.7,16899.3,437575,-12.3,Akio Toyoda,Motor Vehicles and Parts,Motor Vehicles & Parts,8.0,Japan,"Toyota, Japan",http://www.toyota-global.com,23,364445,157210

### Working with Integer Labels

1. Assign the first five rows of the sorted_emp dataframe to the variable top5_emp, by choosing the correct method out of either loc[] or iloc[].

In [16]:
sorted_emp = f500.sort_values("employees", ascending=False)
top5_emp = sorted_emp.head()

top5_emp

,company,rank,revenues,revenue_change,profits,assets,profit_change,ceo,industry,sector,previous_rank,country,hq_location,website,years_on_global_500_list,employees,total_stockholder_equity
0,Walmart,1,485873,0.8,13643.0,198825,-7.2,C. Douglas McMillon,General Merchandisers,Retailing,1.0,USA,"Bentonville, AR",http://www.walmart.com,23,2300000,77798
3,China National Petroleum,4,262573,-12.3,1867.5,585619,-73.7,Zhang Jianhua,Petroleum Refining,Energy,3.0,China,"Beijing, China",http://www.cnpc.com.cn,17,1512048,301893
118,China Post Group,119,65605,-5.8,4980.3,1221649,18.7,Li Guohua,"Mail, Package, and Freight Delivery",Transportation,105.0,China,"Beijing, China",http://www.chinapost.com.cn,7,941211,43114
1,State Grid,2,315199,-4.4,9571.3,489838,-6.2,Kou Wei,Utilities,Energy,2.0,China,"Beijing, China",http://www.sgcc.com.cn,17,926067,209456
26,Hon Hai Precision Industry,27,135129,-4.3,4608.8,80436,-0.4,Terry Gou,"Electronics, Electrical Equip.",Technology,25.0,Taiwan,"New Taipei City, Taiwan",http://www.foxconn.com,13,726772,33476

### Using pandas methods to create boolean masks
1. Use the Series.notnull() method to select all rows from f500 that have a non-null value for the previous_rank column, and assign the result to previously_ranked
2. From the previously_ranked dataframe, subtract the previous_rank column from the rank column, and assign the result to rank_change.

In [17]:
previously_ranked = f500[f500["previous_rank"].notnull()]
rank_change = previously_ranked["rank"] - previously_ranked["previous_rank"]
print(rank_change)

0        0.0
1        0.0
2       -1.0
3        1.0
4       -3.0
5       -1.0
6        2.0
7       -3.0
8        0.0
9        4.0
10      -1.0
11       2.0
12      -4.0
13      -4.0
14       2.0
15       2.0
16       1.0
17      -2.0
18      -4.0
19       1.0
20       0.0
21       7.0
22      -5.0
23      -3.0
24      -8.0
25     -18.0
26       2.0
27       6.0
28      -7.0
29       6.0
       ...
455      1.0
457     58.0
459     38.0
460    -31.0
462     44.0
464     19.0
465     15.0
467      9.0
468     77.0
469     35.0
470    -16.0
471     27.0
473     -9.0
474     14.0
475     92.0
476    -17.0
478     50.0
479      8.0
480     -9.0
481     -6.0
483     18.0
485     55.0
486     13.0
488     64.0
489    107.0
490     20.0
492     89.0
496     70.0
497     61.0
498     32.0
Length: 467, dtype: float64

### Using Boolean Operators

1. Select from the f500 dataframe:
    - Companies with revenues over 100 billion and negative profits, assigning the result to big_rev_neg_profit.
    - The first 5 companies in the Technology sector that are not headquartered in the USA, assigning the result to tech_outside_usa.

In [20]:
big_rev_neg_profit = f500[(f500["revenues"] > 100000) & (f500["profits"] < 0)]
tech_outside_usa = f500[(f500["sector"] == "Technology") & (~(f500["country"] == "USA"))].head()

print(big_rev_neg_profit)
tech_outside_usa

                company  rank  revenues  revenue_change  profits   assets  \
32  Japan Post Holdings    33    122990             3.6   -267.4  2631385
44              Chevron    45    107567           -18.0   -497.0   260078

    profit_change               ceo                         industry  \
32         -107.5  Masatsugu Nagato  Insurance: Life, Health (stock)
44         -110.8    John S. Watson               Petroleum Refining

        sector  previous_rank country    hq_location                  website  \
32  Financials           37.0   Japan   Tokyo, Japan  http://www.japanpost.jp
44      Energy           31.0     USA  San Ramon, CA   http://www.chevron.com

    years_on_global_500_list  employees  total_stockholder_equity
32                        21     248384                     91532
44                        23      55200                    145556

,company,rank,revenues,revenue_change,profits,assets,profit_change,ceo,industry,sector,previous_rank,country,hq_location,website,years_on_global_500_list,employees,total_stockholder_equity
14,Samsung Electronics,15,173957,-2.0,19316.5,217104,16.8,Oh-Hyun Kwon,"Electronics, Electrical Equip.",Technology,13.0,South Korea,"Suwon, South Korea",http://www.samsung.com,23,325000,154376
26,Hon Hai Precision Industry,27,135129,-4.3,4608.8,80436,-0.4,Terry Gou,"Electronics, Electrical Equip.",Technology,25.0,Taiwan,"New Taipei City, Taiwan",http://www.foxconn.com,13,726772,33476
70,Hitachi,71,84558,1.2,2134.3,86742,48.8,Toshiaki Higashihara,"Electronics, Electrical Equip.",Technology,79.0,Japan,"Tokyo, Japan",http://www.hitachi.com,23,303887,26632
82,Huawei Investment & Holding,83,78511,24.9,5579.4,63837,-5.0,Ren Zhengfei,Network and Other Communications Equipment,Technology,129.0,China,"Shenzhen, China",http://www.huawei.com,8,180000,20159
104,Sony,105,70170,3.9,676.4,158519,-45.1,Kazuo Hirai,"Electronics, Electrical Equip.",Technology,113.0,Japan,"Tokyo, Japan",http://www.sony.net,23,128400,22415

### Pandas Index Alignment

**Earlier, we created the rank_change series by performing vectorized subtraction only on rows without null values. We have included the code again as a reminder.**

1. Assign the values in the rank_change to a new column in the f500 dataframe, "rank_change".
2. Once you have run your code, use the variable inspector to look at the f500 dataframe and observe how the new column aligns with the existing data.

In [22]:
previously_ranked = f500[f500["previous_rank"].notnull()]
rank_change = previously_ranked["previous_rank"] - previously_ranked["rank"]
f500["rank_change"] = rank_change

f500['rank_change'].head()

0    0.0
1    0.0
2    1.0
3   -1.0
4    3.0
Name: rank_change, dtype: float64

### Using Loops with Pandas

**We're going to produce the following dictionary of the top employer in each country:**

**{'Australia': 'Wesfarmers',<br>
 'Belgium': 'Anheuser-Busch InBev',<br>
 'Brazil': 'JBS',<br>
 ...<br>
 'U.A.E': 'Emirates Group',<br>
 'USA': 'Walmart',<br>
 'Venezuela': 'Mercantil Servicios Financieros'}**<br>
 
1. Read the documentation for the DataFrame.sort_values() method to familiarize yourself with the syntax. You will need to use only the by and ascending parameters to complete this exercise.
2. Create an empty dictionary, top_employer_by_country to store the results of the exercise.
3. Use the Series.unique() method to create an array of unique values from the country column.
4. Use a for loop to iterate over the array unique countries, and in each iteration:
    - Select only the rows that have a country name equal to the current iteration.
    - Use DataFrame.sort_values() to sort those rows by the employees column in descending order.
    - Select the first row from the sorted dataframe.
    - Extract the company name from the index label company from the first row.
    - Assign the results to the top_employer_by_country dictionary, using the country name as the key, and the company name as the value.
5. When you have run your code, use the variable inspector to view the top employer for each country.

In [23]:
top_employer_by_country = {}
unique_country = f500["country"].unique()

for c in unique_country:
    sorted_companies = f500[f500["country"] == c].sort_values(by="employees", ascending=False)
    employer_row = sorted_companies["company"]
    top_employer = employer_row.iloc[0]
    top_employer_by_country[c] = top_employer
    
top_employer_by_country

{'USA': 'Walmart',
 'China': 'China National Petroleum',
 'Japan': 'Toyota Motor',
 'Germany': 'Volkswagen',
 'Netherlands': 'EXOR Group',
 'Britain': 'Compass Group',
 'South Korea': 'Samsung Electronics',
 'Switzerland': 'Nestle',
 'France': 'Sodexo',
 'Taiwan': 'Hon Hai Precision Industry',
 'Singapore': 'Flex',
 'Italy': 'Poste Italiane',
 'Russia': 'Gazprom',
 'Spain': 'Banco Santander',
 'Brazil': 'JBS',
 'Mexico': 'America Movil',
 'Luxembourg': 'ArcelorMittal',
 'India': 'State Bank of India',
 'Malaysia': 'Petronas',
 'Thailand': 'PTT',
 'Australia': 'Wesfarmers',
 'Belgium': 'Anheuser-Busch InBev',
 'Norway': 'Statoil',
 'Canada': 'George Weston',
 'Ireland': 'Accenture',
 'Indonesia': 'Pertamina',
 'Denmark': 'Maersk Group',
 'Saudi Arabia': 'SABIC',
 'Sweden': 'H & M Hennes & Mauritz',
 'Finland': 'Nokia',
 'Venezuela': 'Mercantil Servicios Financieros',
 'Turkey': 'Koc Holding',
 'U.A.E': 'Emirates Group',
 'Israel': 'Teva Pharmaceutical Industries'}

### Challenge: Calculating Return on Assets by Sector
1. Create a new column roa in the f500 dataframe, containing the return on assets metric for each company.
2. Aggregate the data by the sector column, and create a dictionary top_roa_by_sector, with:
    - Dictionary keys with the sector name.
    - Dictionary values with the company name with the highest ROA value from that sector.

In [25]:
f500["roa"] = f500["profits"]/f500["assets"]
top_roa_by_sector = {}

companies_by_sector = f500["sector"].unique()

for i in companies_by_sector:
    company_df = f500[f500["sector"] == i].sort_values(by="roa", ascending=False)
    company_series = company_df["company"]
    top_company = company_series.iloc[0]
    top_roa_by_sector[i] = top_company
    
top_roa_by_sector

{'Retailing': 'H & M Hennes & Mauritz',
 'Energy': 'National Grid',
 'Motor Vehicles & Parts': 'Subaru',
 'Financials': 'Berkshire Hathaway',
 'Technology': 'Accenture',
 'Wholesalers': 'McKesson',
 'Health Care': 'Gilead Sciences',
 'Telecommunications': 'KDDI',
 'Engineering & Construction': 'Pacific Construction Group',
 'Industrials': '3M',
 'Food & Drug Stores': 'Publix Super Markets',
 'Aerospace & Defense': 'Lockheed Martin',
 'Food, Beverages & Tobacco': 'Philip Morris International',
 'Household Products': 'Unilever',
 'Transportation': 'Delta Air Lines',
 'Materials': 'CRH',
 'Chemicals': 'LyondellBasell Industries',
 'Media': 'Disney',
 'Apparel': 'Nike',
 'Hotels, Restaurants & Leisure': 'McDonald’s',
 'Business Services': 'Adecco Group'}